apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql
  namespace: sqldb
  labels:
    app: mysql
spec:
  containers:
    - name: myodico-mysql
      image: 967243465572.dkr.ecr.us-east-1.amazonaws.com/myodico-mysql:mysql-v5.6
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "db_pass123"
      ports:
        - containerPort: 3306
