apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-mysql
  namespace: sqldb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: myodico-mysql
          image: 967243465572.dkr.ecr.us-east-1.amazonaws.com/myodico-mysql:mysql-v5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345"
          ports:
            - containerPort: 3306
