apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replica
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
        - name: myodico-webapp
          image: 967243465572.dkr.ecr.us-east-1.amazonaws.com/myodico-webapp:application-v2.1
          env:
            - name: DBPWD
              value: "db_pass123"
            - name: DBUSER
              value: root
            - name: DBHOST
              value: "mysql-service.sqldb.svc.cluster.local"
            - name: DBPORT
              value: "3306"
          ports:
            - containerPort: 8080
